import 'dart:io';

import 'package:timezone/data/latest.dart' as compact_data;
import 'package:timezone/data/latest_all.dart' as complete_data;
import 'package:timezone/timezone.dart' as tz;

void main() {
  complete_data.initializeTimeZones();
  final complete = Map<String, tz.Location>.from(tz.timeZoneDatabase.locations);

  compact_data.initializeTimeZones();
  final compact = Map<String, tz.Location>.from(tz.timeZoneDatabase.locations);
  final canonicalsBySignature = <String, List<String>>{};
  for (final entry
      in compact.entries.toList()
        ..sort((left, right) => left.key.compareTo(right.key))) {
    canonicalsBySignature
        .putIfAbsent(_futureSignature(entry.value), () => <String>[])
        .add(entry.key);
  }

  final aliases = <String, String>{};
  for (final entry in complete.entries) {
    if (compact.containsKey(entry.key)) continue;
    final candidates = canonicalsBySignature[_futureSignature(entry.value)];
    if (candidates == null || candidates.isEmpty) {
      throw StateError('No compact time-zone match for ${entry.key}.');
    }
    final region = entry.key.split('/').first;
    aliases[entry.key] =
        _preferredAliases[entry.key] ??
        candidates.firstWhere(
          (candidate) => candidate.split('/').first == region,
          orElse: () => candidates.first,
        );
  }

  final output = StringBuffer()
    ..writeln('// GENERATED by tool/generate_timezone_aliases.dart.')
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln('const timeZoneAliases = <String, String>{');
  for (final entry
      in aliases.entries.toList()
        ..sort((left, right) => left.key.compareTo(right.key))) {
    output.writeln("  '${entry.key}': '${entry.value}',");
  }
  output.writeln('};');
  File('lib/time_zone_aliases.dart').writeAsStringSync(output.toString());
  stdout.writeln('Generated ${aliases.length} time-zone aliases.');
}

const _preferredAliases = <String, String>{
  'Europe/Amsterdam': 'Europe/Brussels',
};

String _futureSignature(tz.Location location) {
  final values = <String>[];
  for (var year = 2020; year <= 2045; year++) {
    for (var month = 1; month <= 12; month++) {
      final instant = DateTime.utc(year, month, 1, 12).millisecondsSinceEpoch;
      final zone = location.timeZone(instant);
      values.add('${zone.offset.inMinutes}:${zone.isDst ? 1 : 0}');
    }
  }
  return values.join(',');
}
